### ISSUE TITLE
后台显示xxx已拒绝连接

### ISSUE THREAD

**Issue by Steven-WZH** [halo-sigs/plugin-umami#13]
![image](https://user-images.githubusercontent.com/113268133/229260529-661dc941-abb3-4ee0-82b6-ea247e06a01f.png)

**Comment by Frank683456** [comment]
我也是这个问题

**Comment by ruibaby** [comment]
这个方法有试过吗？

https://github.com/halo-sigs/plugin-umami#faq

**Comment by LeslieLeung** [comment]
我的umami是在vercel上部署的，无法更改cors设置，有对应的解决方案吗？

**Comment by askfname** [comment]
同样的问题，挂服务器的代理甚至连 Umami 的网站都访问不了

**Comment by acanyo** [comment]
怎么解决的呢 我按照faq无法解决呢
