### ISSUE TITLE
---

### ISSUE THREAD

**Issue by QYG2297248353** [halo-sigs/plugin-umami#28]
---

**Comment by QYG2297248353** [comment]
@ruibaby 是否可以修复一下啊

**Comment by ruibaby** [comment]
我不清楚这是否和此插件有关，此插件的作用仅仅是插入 umami 的跟踪代码。建议检查 umami。

**Comment by QYG2297248353** [comment]
其实更推荐使用编程式实现

https://umami.is/docs/api/sending-stats

可以埋点到操作过程中
前后台就可以分开统计

**Comment by QYG2297248353** [comment]
![image](https://github.com/user-attachments/assets/b6821ced-0d93-4f57-93de-0003023cf8ff)

我是怀疑 异步造成的,不知如何排查此问题，因为在其他网站一切正常
@ruibaby

**Comment by ruibaby** [comment]
> ![image](https://github.com/user-attachments/assets/b6821ced-0d93-4f57-93de-0003023cf8ff)
> 
> 
> 
> 我是怀疑 异步造成的,不知如何排查此问题，因为在其他网站一切正常
> 
> @ruibaby 

你可以不用这个插件，直接在设置的代码注入添加 Umami 提供的代码。

**Comment by ruibaby** [comment]
> 其实更推荐使用编程式实现
> 
> 
> 
> https://umami.is/docs/api/sending-stats
> 
> 
> 
> 可以埋点到操作过程中
> 
> 前后台就可以分开统计

PR welcome

**Comment by QYG2297248353** [comment]
> > 其实更推荐使用编程式实现
> > https://umami.is/docs/api/sending-stats
> > 可以埋点到操作过程中
> > 前后台就可以分开统计
> 
> PR welcome

等有时间吧，虽然很感兴趣 halo 的插件开发

**Comment by QYG2297248353** [comment]
> 你可以不用这个插件，直接在设置的代码注入添加 Umami 提供的代码。

确实是，影响不大
