### ISSUE TITLE
https的域名是不是用不了这个插件呀？

### ISSUE THREAD

**Issue by git-kings** [halo-sigs/plugin-umami#6]

**Comment by ruibaby** [comment]
目前遇到了什么问题？

**Comment by git-kings** [comment]
> 

解决完毕了

**Comment by ruibaby** [comment]
@git-kings 可以说明一下遇到的问题和解决方式吗？可以方便后面遇到同样问题的人。

**Comment by git-kings** [comment]
直接配置umami的插件配置完毕后是不能直接访问成功的；
我的做法是：
	1.申请了二级域名，申请SSL证书，并在Nginx配置https
	2.此时配置完毕后再次到halo后台访问Umami插件的地图提示"拒接我们的链接"
	3.这时候我们根据提示添加更改下Nginx的配置
	server{
    		listen 443 ssl http2;
    		server_name [umami.domain.com];
    		#...
    		add_header Access-Control-Allow-Origin 'https://halo.domain.com';
    		add_header Access-Control-Allow-Methods 'GET, POST, OPTIONS';
    		add_header Access-Control-Allow-Headers 'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization';
		    if ($request_method = 'OPTIONS') {
		        return 204;
		    }

		    add_header Content-Security-Policy 'frame-ancestors halo.domain.com';
		    location / {
		    		#...
		    		proxy_hide_header 'Access-Control-Allow-Origin';
		    		proxy_hide_header 'Content-Security-Policy';
		    }
		}
		然后我们重启Nginx即可正常访问halo后台的Umami地图

	如果有需要我可以出一个完整流程的说明文档，从我配置umami到能正常访问，这期间我确实遇到好多坑

**Comment by ruibaby** [comment]
@git-kings 这是因为 Umami 在最新的版本禁止了 iframe 引用，后面也有人提供了解决方案：https://github.com/halo-sigs/plugin-umami#faq

后续看是否有必要向 Umami 提交 issue 以解决此问题。
